package z10

import (
	"bytes"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"slices"
	"strings"

	"github.com/router-for-me/CLIProxyAPI/v8/internal/config"
	log "github.com/sirupsen/logrus"
	"gopkg.in/yaml.v3"
)

// friendKeyPrefix starts every key generated by the admin API.
const friendKeyPrefix = "sk-z10-"

// friendsFileHeader marks friends.yaml as written by the admin API.
const friendsFileHeader = "# Managed by the z10 admin API (/z10/friends). Comments and formatting are not preserved.\n"

// adminError is an admin request rejected with an HTTP status and a message.
type adminError struct {
	status  int
	message string
}

// editFriends applies edit to the entries of the active friends.yaml content, validates
// the result with the loader's parser and owner-key rule, replaces friends.yaml
// atomically, and activates the new keys at once. Nothing is written when edit or the
// validation fails. target names the entry the edit creates or changes ("" if none);
// it must not collide with an owner key. The edit runs under rt.mu, so name checks
// inside it are race-free.
func (rt *Runtime) editFriends(target string, edit func([]friendEntry, *config.Config) ([]friendEntry, *adminError)) (*FriendSet, *adminError) {
	rt.mu.Lock()
	defer rt.mu.Unlock()

	current := rt.state.Load()
	entries, errEdit := edit(friendEntries(current.parsed), current.owner)
	if errEdit != nil {
		return nil, errEdit
	}
	data, errEncode := encodeFriends(entries)
	if errEncode != nil {
		log.WithError(errEncode).Error("z10: failed to encode friends.yaml")
		return nil, &adminError{http.StatusInternalServerError, "failed to encode " + FriendsFileName}
	}
	parsed, errParse := ParseFriends(data)
	if errParse != nil {
		return nil, &adminError{http.StatusBadRequest, errParse.Error()}
	}
	if target != "" {
		if _, dropped := parsed.withoutKeys(current.owner.APIKeys); slices.Contains(dropped, target) {
			return nil, &adminError{http.StatusBadRequest, fmt.Sprintf("the key of friend %q equals an owner API key", target)}
		}
	}
	if errWrite := writeFileAtomic(rt.friendsPath, bytes.TrimRight(data, "\n")); errWrite != nil {
		log.WithError(errWrite).Error("z10: failed to write friends.yaml")
		return nil, &adminError{http.StatusInternalServerError, "failed to write " + FriendsFileName}
	}
	// The watcher reloads the same content afterwards, which changes nothing.
	_ = rt.storeLocked(current, current.owner, parsed)
	return parsed, nil
}

// friendEntries converts a parsed set back to file entries, keeping order and keys.
func friendEntries(set *FriendSet) []friendEntry {
	friends := set.Friends()
	entries := make([]friendEntry, 0, len(friends))
	for _, friend := range friends {
		enabled := friend.Enabled
		entries = append(entries, friendEntry{
			Name:     friend.Name,
			Key:      friend.key,
			Models:   slices.Clone(friend.Models),
			Channels: slices.Clone(friend.Channels),
			Expires:  friend.ExpiresRaw,
			Enabled:  &enabled,
		})
	}
	return entries
}

func findEntry(entries []friendEntry, name string) int {
	return slices.IndexFunc(entries, func(entry friendEntry) bool { return entry.Name == name })
}

func encodeFriends(entries []friendEntry) ([]byte, error) {
	var buffer bytes.Buffer
	buffer.WriteString(friendsFileHeader)
	encoder := yaml.NewEncoder(&buffer)
	encoder.SetIndent(2)
	if errEncode := encoder.Encode(friendsDocument{Keys: entries}); errEncode != nil {
		return nil, errEncode
	}
	if errClose := encoder.Close(); errClose != nil {
		return nil, errClose
	}
	return buffer.Bytes(), nil
}

// newFriendKey returns "sk-z10-" followed by 32 random bytes in unpadded base64url.
func newFriendKey() (string, error) {
	var raw [32]byte
	if _, errRead := rand.Read(raw[:]); errRead != nil {
		return "", errRead
	}
	return friendKeyPrefix + base64.RawURLEncoding.EncodeToString(raw[:]), nil
}

// enabledChannels returns the names of the openai-compatibility entries that are not
// disabled, in config order, one per provider key.
func enabledChannels(owner *config.Config) []string {
	var names []string
	seen := map[string]struct{}{}
	for _, compat := range owner.OpenAICompatibility {
		name := strings.TrimSpace(compat.Name)
		if compat.Disabled || name == "" {
			continue
		}
		providerKey := channelProviderKey(name)
		if _, duplicate := seen[providerKey]; duplicate {
			continue
		}
		seen[providerKey] = struct{}{}
		names = append(names, name)
	}
	return names
}

// resolveChannels checks requested channel names against the enabled
// openai-compatibility entries and returns them as spelled in config.yaml.
func resolveChannels(owner *config.Config, requested []string) ([]string, error) {
	if len(requested) == 0 {
		return nil, errors.New("channels must not be empty")
	}
	byProviderKey := map[string]string{}
	for _, name := range enabledChannels(owner) {
		byProviderKey[channelProviderKey(name)] = name
	}
	var channels []string
	for _, channel := range requested {
		name, known := byProviderKey[channelProviderKey(channel)]
		if strings.TrimSpace(channel) == "" || !known {
			return nil, fmt.Errorf("channel %q is not an enabled openai-compatibility channel", channel)
		}
		if !slices.Contains(channels, name) {
			channels = append(channels, name)
		}
	}
	return channels, nil
}

// cleanModels trims model patterns and requires at least one non-empty pattern.
func cleanModels(models []string) ([]string, error) {
	if len(models) == 0 {
		return nil, errors.New("models must not be empty")
	}
	cleaned := make([]string, 0, len(models))
	for _, model := range models {
		model = strings.TrimSpace(model)
		if model == "" {
			return nil, errors.New("models must not contain an empty pattern")
		}
		cleaned = append(cleaned, model)
	}
	return cleaned, nil
}

// cleanExpires validates an expiry with the loader's parser; "" means never.
func cleanExpires(raw string) (string, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", nil
	}
	if _, errExpires := parseExpiry(raw); errExpires != nil {
		return "", errExpires
	}
	return raw, nil
}
